title: 'NWM-2.1-grid1km-LDAS'
description: >
  Three-hourly output from 40 years. 
pangeo_forge_version: '0.9.0'
pangeo_notebook_version: '2022.07.13'
recipes:
  - id: NWM-2.1-grid1km-LDAS
    object: 'recipe:recipe'
provenance:
  providers:
    - name: 'NOAA National Water Center'
      description: 'Parker MacCready, Professor, University of Washington'
      orcid: '0000-0002-8070-8062'
      github: rsignell-usgs
      roles:
        - provider
        - licensor
      url: https://faculty.washington.edu/pmacc/LO/LiveOcean.html
  license: 'CC0'
maintainers:
  - name: 'Rich Signell'
    orcid: '0000-0003-0682-9613'
    github: rsignell
bakery:
  id: 'pangeo-ldeo-nsf-earthcube'
